[package]
name = "BaptSwapV2"
version = "0.0.1"
authors = []

[addresses]

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.BaptSwap]
local = ".."

[dev-dependencies]
